resolver: lts-14.12
packages:
- squeal-postgresql

extra-deps:
- github: morphismtech/free-categories
  commit: 33b5d9e0345ff59c5be3bdb7257c70b1977e5c67
- github: mwotton/binary-parser
  commit: 6b1ea18fe70785da52964050a4b30144e3f48fce
